version: '0.1.0-rev{build}'
clone_depth: 5
environment:
  TARGET: x86_64-pc-windows-msvc
  RUST_BACKTRACE: full
  matrix:
  - PYTHON: "C:\\Python35-x64"
  - PYTHON: "C:\\Python36-x64"
  - PYTHON: "C:\\Python37-x64"
  - PYTHON: "C:\\Python38-x64"

install:
- ps: .\ci\appveyor\install.ps1
- "%PYTHON%\\python.exe -m pip install -U -r ci/requirements.txt"

before_build:
- "%PYTHON%\\python.exe -V"

build_script:
- "%PYTHON%\\python.exe setup.py build_ext --inplace --debug"

test_script:
- "%PYTHON%\\python.exe setup.py test"

before_deploy:
- "%PYTHON%\\python.exe setup.py sdist bdist_wheel"

deploy_script:
- ps: .\ci\appveyor\deploy.ps1
