dist: bionic
language: python
cache: pip

stages:
  - name: Test (Linux)
  - name: Test (OSX)

env:
  global:
    - PATH="$PYENV_ROOT/bin:$PATH"
    - PYENV_ROOT="$HOME/.pyenv"

.test-linux: &test-linux
  os: linux
  dist: bionic
  stage: Test (Linux)
  language: python
  cache: pip
  services: docker
  before_install: ci/travis/manylinux/before_install.sh
  install: ci/travis/manylinux/install.sh
  script: ci/travis/manylinux/script.sh
  after_success: ci/travis/manylinux/after_success.sh
  before_deploy: ci/travis/manylinux/before_deploy.sh

.test-osx: &test-osx
  os: osx
  stage: Test (OSX)
  language: generic
  cache:
    pip: true
    directories:
      - $HOME/Library/Caches/Homebrew
      - $HOME/.pyenv_cache
  install: ci/travis/osx/install.sh
  script: ci/travis/osx/script.sh
  before_cache: ci/travis/osx/before_cache.sh
  before_deploy: ci/travis/osx/before_deploy.sh
  after_success: ci/travis/osx/after_success.sh

jobs:
  include:
    # Linux
    - python: pypy3
      if: tag IS present
      <<: *test-linux
    - python: 3.5
      if: tag IS present
      <<: *test-linux
    - python: 3.6
      if: tag IS present
      <<: *test-linux
    - python: 3.7
      if: tag IS present
      <<: *test-linux
    - python: 3.8
      <<: *test-linux
    # OSX
    - env: PYTHON=python3.5
      name: "Python: 3.5"
      if: tag IS present
      <<: *test-osx
    - env: PYTHON=python3.6
      name: "Python: 3.6"
      if: tag IS present
      <<: *test-osx
    - env: PYTHON=python3.7
      name: "Python: 3.7"
      if: tag IS present
      <<: *test-osx
    - env: PYTHON=python3.8
      name: "Python: 3.8"
      <<: *test-osx

deploy:
  provider: script
  script: ci/travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: althonos/pyhcrf

notifications:
  email:
  - althonosdev@gmail.com
